[workspace]

resolver = "2"

members = [
	"api",
	"common/derive",
	"common/domain",
	"common/infrastructure",
	"common/presentation",
	"common/testing",
	"common/olog",
	"github-indexer",
	"application/rest-api-adapter",
]
