[workspace]

resolver = "2"

members = [
	"api/bootstrap",
	"common/derive",
	"common/domain",
	"common/infrastructure",
	"common/presentation",
	"common/testing",
	"common/olog",
	"github-indexer",
]
