[workspace]

members = [
  "api",
  "common/derive",
  "common/domain",
  "common/infrastructure",
  "common/presentation",
  "common/testing",
  "common/olog",
  "event-listeners",
  "event-store",
]
