table:
  name: applications
  schema: public
select_permissions:
  - role: public
    permission:
      columns:
        - id
        - received_at
        - project_id
        - applicant_id
      filter: {}
