default:
  coinmarketcap:
    api_key: $COINMARKETCAP_API_KEY
    currencies:
      USD: "2781"
      ETH: "1027"
      OP: "11840"
      APT: "21794"
  database:
    url: $DATABASE_URL
    pool_max_size: 3
