name: Setup environment

description: Run DB, RabbitMQ, Hasura, etc. and run database migrations

runs:
  using: "composite"
  steps:
    - name: Run docker-compose
      shell: bash
      run: make infra/up
