default:
  amqp:
    connection_retry_interval_ms: 6000
    connection_retry_count: 100
  database:
    url: $DATABASE_URL

local:
  amqp:
    url: $AMQP_URL
  database:
    pool_max_size: 3
  tracer:
    json: false
    ansi: true
    location: true

production:
  amqp:
    url: $CLOUDAMQP_URL
  database:
    pool_max_size: 3
  tracer:
    json: true
    ansi: false
    location: true
