default:
  amqp:
    connection_retry_interval_ms: 6000
    connection_retry_count: 100
  coinmarketcap:
    api_key: $COINMARKETCAP_API_KEY
    currencies:
      USD: "2781"
      ETH: "1027"
      OP: "11840"
      APT: "21794"
  database:
    pool_max_size: 3
    url: $DATABASE_URL
  github:
    base_url: $GITHUB_BASE_URL
    personal_access_tokens: $GITHUB_PAT
    max_calls_per_request: $GITHUB_MAX_CALLS_PER_REQUEST
  http:
    api_keys:
      - $GITHUB_INDEXER_API_KEY

local:
  amqp:
    url: $AMQP_URL
  tracer:
    json: false
    ansi: true
    location: true

production:
  amqp:
    url: $CLOUDAMQP_URL
  tracer:
    json: true
    ansi: false
    location: true
